name: "Terraform Monorepo CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-lint:
    name: "Validate, Lint & Scan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0

      - name: Run Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Init and Validate Modules
        run: |
          for dir in $(find modules environments -maxdepth 2 -type d); do
            if [ -f "$dir/main.tf" ] || [ -f "$dir/providers.tf" ]; then
              echo "==> Validating $dir"
              terraform -chdir="$dir" init -backend=false
              terraform -chdir="$dir" validate
            fi
          done

      - name: Run TFLint
        run: |
          tflint --init --config=$(pwd)/.tflint.hcl
          tflint --config=$(pwd)/.tflint.hcl --recursive

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-shortcut-table: 'true'
          output: 'trivy-results.sarif'
